### ISSUE TITLE
some typos and issues inn scaffold/README.md

### ISSUE THREAD

**Issue by obar1** [jyates/manning-energy-resources#1]
- [ ] `manning-postgres` should be used everywhere

- [ ] `secret-pw` is mysql password not `secret` only 

- [ ] small improvements about the bash cmd

**Comment by jyates** [comment]
Thanks for contribution! I'm out of town through the weekend, but will look
at this Monday!

**Comment by jyates** [comment]
PR lg so far. Do you want me to merge it?

**Comment by jyates** [comment]
Thanks for the contribution! It is very much appreciated!
